// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Vs6kgRd41FG0z-XQueUPGtLuWuhEC_Q',
    appId: '1:1044474172586:web:9b0dcb6e384ed722896cd3',
    messagingSenderId: '1044474172586',
    projectId: 'calci-d4cb2',
    authDomain: 'calci-d4cb2.firebaseapp.com',
    storageBucket: 'calci-d4cb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9sfTD6tLFGYzf-dharUb21jMtiuE1xVc',
    appId: '1:1044474172586:android:f5b9fad57b62976d896cd3',
    messagingSenderId: '1044474172586',
    projectId: 'calci-d4cb2',
    storageBucket: 'calci-d4cb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnarJMssbZRZQGFjCHoCuf0K0YApaz_uU',
    appId: '1:1044474172586:ios:2b93f5a3d05f33c5896cd3',
    messagingSenderId: '1044474172586',
    projectId: 'calci-d4cb2',
    storageBucket: 'calci-d4cb2.firebasestorage.app',
    iosBundleId: 'com.example.gymassistanat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnarJMssbZRZQGFjCHoCuf0K0YApaz_uU',
    appId: '1:1044474172586:ios:2b93f5a3d05f33c5896cd3',
    messagingSenderId: '1044474172586',
    projectId: 'calci-d4cb2',
    storageBucket: 'calci-d4cb2.firebasestorage.app',
    iosBundleId: 'com.example.gymassistanat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Vs6kgRd41FG0z-XQueUPGtLuWuhEC_Q',
    appId: '1:1044474172586:web:f97269f688cc0bc3896cd3',
    messagingSenderId: '1044474172586',
    projectId: 'calci-d4cb2',
    authDomain: 'calci-d4cb2.firebaseapp.com',
    storageBucket: 'calci-d4cb2.firebasestorage.app',
  );
}
